- name: Setup Devops Server Environment
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ec2-user
  gather_facts: yes
  vars:
    #dev_environment: "{{ lookup('env','TF_VAR_var_dev_environment') }}"
    #var_name: "{{ lookup('env','TF_VAR_var_name') }}"
    var_name: blizzard
    dev_environment: stage
    chat: "{{ lookup('env','TF_VAR_var_chat') }}"
    sign: "{{ lookup('env','TF_VAR_var_sign') }}"
    lyrics: "{{ lookup('env','TF_VAR_var_lyrics') }}"
    commerce: "{{ lookup('env','TF_VAR_var_commerce') }}"
    ments: "{{ lookup('env','TF_VAR_var_ments') }}"
    payweb: "{{ lookup('env','TF_VAR_var_payweb') }}"
    user: "{{ lookup('env','TF_VAR_var_user') }}"
  roles:
    - common
    - devops-service-server
    - devops-service-push
    - appweb
    - { role: devops-service-chat, when: chat == '1' }
    - { role: devops-service-ments, when: ments == '1' }
    - { role: devops-service-lyrics, when: lyrics == '1' }
    - { role: devops-service-commerce, when: commerce == '1' }
    - { role: payweb, when: payweb == '1' }
    - { role: user-server, when: user == '1' }
    - { role: sign-server, when: sign == '1' }
    - nginx
    - docker_containers
