version: "3"
services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "{{ var_name }}-redis-server-1"
    hostname: "{{ var_name }}-redis-1"
    ports:
      - "6379:6379"
    environment:
      REDIS_REPLICATION_MODE: master
    volumes:
      - /devops/docker-compose/redis/data-redis:/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
       - net.core.somaxconn=512
    restart: unless-stopped
networks:
  default:
    external:
      name: rabbitmq_default
