---
- name: Create directory structure
  file:
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    state: directory
  with_items:
    - /devops/shelf/{{ service }}
    - /devops/services/{{ service }}

- name: Unpack archive
  unarchive:
    src: /tmp/schedule-server/schedule-server.tar
    dest: /devops/services/{{ service }}
    owner: "{{ user }}"
    group: "{{ user }}"
    list_files: true
    mode: 0755

- name: Copy schedule-server.service to init.d
  template:
    src: schedule-server.service.j2
    dest: /etc/init.d/{{ service }}
    owner: root
    group: root
    mode: 0755

- name: Enable schedule-server and daemon reload
  systemd:
    name: schedule-server
    enabled: yes
    daemon_reload: yes
