- name: Setup Octopus Server Environment
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ec2-user
  gather_facts: yes
  vars:
    dev_environment: "test"
    var_name: "devops"
  roles:
    - common
    - octopus-octopush
    - octopus-chat
    - octopus-analytics
    - octopus-comments
    - octopus-subscription
    - signaling-server
    - quizz-server
    - schedule-server
    - docker_containers
